# Generated by Django 4.1.5 on 2023-02-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(default='')),
                ('name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', models.BigIntegerField(default='')),
                ('course', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c++', 'C++'), ('web design', 'Web Design'), ('dot net', 'Dot Net'), ('testing', 'Testing'), ('data science', 'Data Science'), ('data analytics', 'Data Analytics')], default='python', max_length=20)),
                ('doj', models.DateField(default='')),
            ],
        ),
    ]
